// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADsxD1SCeCkM4L_a8xl4IFVLIhulopQOw',
    appId: '1:473867559991:web:26f4342dfd9085d4a20bb2',
    messagingSenderId: '473867559991',
    projectId: 'attendoproject',
    authDomain: 'attendoproject.firebaseapp.com',
    storageBucket: 'attendoproject.firebasestorage.app',
    measurementId: 'G-WFHBDQP78R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACumlOTMZmxSKzN4rK3X9c-1R4UzZXuVA',
    appId: '1:473867559991:android:91a1fee4b8342252a20bb2',
    messagingSenderId: '473867559991',
    projectId: 'attendoproject',
    storageBucket: 'attendoproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJEaw_V_-lT9I4iYkNSrhfqz3tPLVBGA',
    appId: '1:473867559991:ios:9b6ef4569a969e88a20bb2',
    messagingSenderId: '473867559991',
    projectId: 'attendoproject',
    storageBucket: 'attendoproject.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJEaw_V_-lT9I4iYkNSrhfqz3tPLVBGA',
    appId: '1:473867559991:ios:9b6ef4569a969e88a20bb2',
    messagingSenderId: '473867559991',
    projectId: 'attendoproject',
    storageBucket: 'attendoproject.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADsxD1SCeCkM4L_a8xl4IFVLIhulopQOw',
    appId: '1:473867559991:web:f30f31fb03a90687a20bb2',
    messagingSenderId: '473867559991',
    projectId: 'attendoproject',
    authDomain: 'attendoproject.firebaseapp.com',
    storageBucket: 'attendoproject.firebasestorage.app',
    measurementId: 'G-M6NMJQMSYT',
  );
}
